linters:
  enable-all: true
  fast: false
  disable:
    - maligned
    - prealloc
    - wsl

linters-settings:
  lll:
    line-length: 140

issues:
  exclude-rules:
    # Exclude some linters from tests
    - path: _test\.go
      linters:
        - funlen
        - lll
        - goconst
