version: "2"
linters:
  default: all
  disable:
    - prealloc
    - wsl
    - nlreturn
    - errorlint
    - errname
    - varnamelen
    - exhaustruct
    - ireturn
    - wrapcheck
    - depguard
    - embeddedstructfieldcheck
    - wsl_v5
    - inamedparam

  settings:
    lll:
      line-length: 150

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

    rules:
      # Exclude some linters from tests
      - path: _test\.go
        linters:
          - funlen
          - lll
          - goconst
          - err113
          - exhaustruct
          - paralleltest
          - forcetypeassert

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports

  exclusions:
    generated: lax
