name: CI
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.23", "1.24", "1.25", "1.26", "1.27"]

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v7

      - name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload to codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.23", "1.24", "1.25", "1.26", "1.27"]

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v7

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.13.2

  staticcheck:
    name: Staticcheck
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.27"]

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v7

      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: "2026.2.1"
          install-go: false
